"use client";

import { useState } from "react";

// Precomputed from the pooled empirical distribution of active players'
// 12-month average ratings (251,137 men, 30,420 women, Apr 2026 snapshot
// window). For each hypothetical participation ratio r (men per woman), the
// expected top-k gap is E[top-k mean of N_men draws] - E[top-k mean of
// (N_men / r) draws], both from the SAME pooled distribution - i.e. the gap
// you'd see from sample size alone if the sexes were statistically identical.
// Generated by analysis.ipynb's Q4 Monte Carlo (6,000 sims per point).
const RATIOS = [1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0, 3.25, 3.5, 3.75, 4.0, 4.25, 4.5, 4.75, 5.0, 5.25, 5.5, 5.75, 6.0, 6.25, 6.5, 6.75, 7.0, 7.25, 7.5, 7.75, 8.26];

const EXPECTED: Record<number, number[]> = {
  25: [0.3, 9.0, 17.4, 25.5, 32.5, 38.8, 44.3, 49.5, 53.8, 58.6, 62.0, 66.1, 69.5, 73.1, 75.9, 78.8, 81.4, 84.2, 86.8, 89.2, 91.3, 93.8, 96.3, 98.5, 100.3, 102.0, 104.9, 106.1, 110.8],
  100: [0.1, 12.4, 22.3, 31.2, 39.3, 46.3, 52.7, 58.9, 64.1, 69.6, 73.9, 78.6, 82.8, 87.1, 91.1, 95.1, 98.2, 102.3, 105.4, 108.5, 111.6, 114.7, 117.7, 120.7, 123.0, 125.4, 128.5, 130.9, 136.2],
  1000: [0.0, 18.6, 34.1, 47.7, 59.7, 70.6, 80.4, 89.6, 98.1, 106.4, 113.8, 121.0, 127.8, 134.4, 140.6, 146.8, 152.1, 157.9, 163.0, 168.3, 173.3, 178.1, 182.7, 187.2, 191.7, 195.7, 200.0, 204.0, 212.0],
};

const OBSERVED: Record<number, number> = { 25: 253.2, 100: 274.8, 1000: 346.3 };

const N_MEN = 251137;
const N_WOMEN = 30420;
const DEPTHS = [25, 100, 1000];

export default function ParticipationSlider() {
  const [depth, setDepth] = useState<number>(25);
  const [idx, setIdx] = useState<number>(RATIOS.length - 1); // start at today

  const ratio = RATIOS[idx];
  const expected = EXPECTED[depth][idx];
  const expectedToday = EXPECTED[depth][RATIOS.length - 1];
  const observed = OBSERVED[depth];
  const residual = observed - expectedToday; // distribution difference, held fixed
  const predicted = residual + expected;
  const closed = observed - predicted;
  // At today's ratio, show the actual headcount from the snapshot rather than
  // the back-computed N_MEN / 8.26 (which rounds to 30,404 and contradicts the
  // 30,420 quoted in the text).
  const women = idx === RATIOS.length - 1 ? N_WOMEN : Math.round(N_MEN / ratio);

  const residualPct = (residual / observed) * 100;
  const samplePct = (expected / observed) * 100;

  return (
    <div className="bg-sage-50 p-8 rounded-lg border border-sage-100">
      <p className="text-xs uppercase tracking-widest text-sage-600 mb-2">Interactive</p>
      <h3 className="text-2xl font-serif mb-2">What happens to the gap as participation equalises?</h3>
      <p className="text-sm text-ink/70 leading-relaxed mb-6">
        Drag the slider to change how many men play for every woman. The green part of the bar is the
        share of today's gap that sample size mathematics predicts, and it shrinks as participation
        equalises. The rose part is the distribution difference, which participation alone does not
        touch.
      </p>

      <div className="flex gap-2 mb-6">
        {DEPTHS.map((d) => (
          <button
            key={d}
            onClick={() => setDepth(d)}
            className={`px-4 py-2 rounded text-sm tracking-wide transition-colors ${
              depth === d
                ? "bg-sage-700 text-paper"
                : "bg-sage-100 text-sage-700 hover:bg-sage-200"
            }`}
          >
            Top {d.toLocaleString()}
          </button>
        ))}
      </div>

      <div className="mb-2 flex justify-between items-baseline">
        <span className="font-medium">
          {ratio === 1 ? "1 man per woman (parity)" : `${ratio.toFixed(2)} men per woman`}
        </span>
        <span className="stat-number text-3xl">{Math.round(predicted)} Elo</span>
      </div>
      <p className="text-xs text-sage-600 mb-3">
        predicted top {depth.toLocaleString()} gap with {women.toLocaleString()} active women
        {idx === RATIOS.length - 1 ? " (today's actual ratio)" : ""}
      </p>

      <div className="w-full h-5 bg-sage-100 rounded-full overflow-hidden flex">
        <div
          className="h-full bg-rose transition-all duration-300"
          style={{ width: `${residualPct}%` }}
          title="Distribution difference"
        />
        <div
          className="h-full bg-matcha transition-all duration-300"
          style={{ width: `${samplePct}%` }}
          title="Sample size effect"
        />
      </div>
      <div className="flex justify-between text-xs text-sage-600 mt-2">
        <span>
          <span className="inline-block w-2 h-2 rounded-full bg-rose mr-1" />
          distribution difference: {Math.round(residual)} Elo ·{" "}
          <span className="font-medium text-sage-700">{Math.round(residualPct)}%</span>
        </span>
        <span>
          <span className="inline-block w-2 h-2 rounded-full bg-matcha mr-1" />
          sample size effect: {Math.round(expected)} Elo ·{" "}
          <span className="font-medium text-sage-700">{Math.round(samplePct)}%</span>
        </span>
      </div>
      <p className="text-[0.7rem] text-sage-500 mt-2 mb-6">
        Percentages are shares of the observed {Math.round(observed)} Elo gap at top{" "}
        {depth.toLocaleString()}. Switch depth above to see the sample size share rise the deeper
        into the rankings you look.
      </p>

      <input
        type="range"
        min={0}
        max={RATIOS.length - 1}
        step={1}
        value={idx}
        onChange={(e) => setIdx(Number(e.target.value))}
        className="w-full accent-[#7A8B6F] cursor-pointer"
        aria-label="Men per woman participation ratio"
      />
      <div className="flex justify-between text-xs text-sage-600 mt-1">
        <span>1 : 1 (equal numbers)</span>
        <span>8.26 : 1 (today)</span>
      </div>

      <p className="text-sm text-ink/70 leading-relaxed mt-6">
        {idx === RATIOS.length - 1 ? (
          <>
            This is chess today: sample size mathematics accounts for {Math.round(samplePct)} percent of
            the observed {Math.round(observed)} Elo top {depth.toLocaleString()} gap.
          </>
        ) : ratio === 1 ? (
          <>
            At equal participation the sample size effect vanishes entirely. The predicted remaining gap,
            about {Math.round(residual)} Elo at top {depth.toLocaleString()}, is the part participation cannot fix: the
            structural difference in how female players are developed, supported, and retained.
          </>
        ) : (
          <>
            At {ratio.toFixed(2)} men per woman, participation maths would close about{" "}
            {Math.round(closed)} Elo of today's top {depth.toLocaleString()} gap, leaving {Math.round(predicted)} Elo.
          </>
        )}
      </p>
    </div>
  );
}
